# Generated by Django 4.1.5 on 2023-01-29 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_specialization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("value", models.FloatField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient", models.CharField(max_length=255)),
                ("age", models.CharField(max_length=3)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Feminino", "Feminino"), ("Masculino", "Masculino")],
                        default="----------",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        choices=[
                            ("Consulta", "Consulta"),
                            ("Retorno", "Retorno"),
                            ("Exame", "Exame"),
                            ("Consulta e Exame", "Consulta e Exame"),
                        ],
                        default="----------",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctor",
                    ),
                ),
                (
                    "recepcionist",
                    models.ForeignKey(
                        default=5,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
