# Generated by Django 4.1.5 on 2023-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recepcionista", "0006_appointment_medication_appointment_sintoms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="exam",
            field=models.TextField(default="A informar..."),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="description",
            field=models.CharField(
                choices=[
                    ("Consulta", "Consulta"),
                    ("Retorno", "Retorno"),
                    ("Consulta e Exame", "Consulta e Exame"),
                    ("Exame", "Exame"),
                ],
                default="----------",
                max_length=20,
            ),
        ),
    ]
