# Generated by Django 4.1.5 on 2023-02-07 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_recepcionist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recepcionista", "0007_appointment_exam_alter_appointment_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="description",
            field=models.CharField(
                choices=[
                    ("Consulta e Exame", "Consulta e Exame"),
                    ("Consulta", "Consulta"),
                    ("Exame", "Exame"),
                    ("Retorno", "Retorno"),
                ],
                default="----------",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient", models.CharField(max_length=255)),
                ("age", models.CharField(max_length=3)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Feminino", "Feminino"), ("Masculino", "Masculino")],
                        default="----------",
                        max_length=10,
                    ),
                ),
                ("type", models.TextField(default="A informar...")),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("status", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=5,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
