# Generated by Django 4.1.5 on 2023-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recepcionista", "0008_alter_appointment_description_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="type_income",
            field=models.CharField(
                choices=[
                    ("Consulta", "Consulta"),
                    ("Retorno", "Retorno"),
                    ("Consulta e Exame", "Consulta e Exame"),
                ],
                default="----------",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="description",
            field=models.CharField(
                choices=[
                    ("Consulta", "Consulta"),
                    ("Retorno", "Retorno"),
                    ("Consulta e Exame", "Consulta e Exame"),
                ],
                default="----------",
                max_length=20,
            ),
        ),
    ]
